### ISSUE TITLE
CC1101 found with partnum: 0 and version: 0

### ISSUE THREAD

**Issue by spupetic** [nistvan86/esphome-q7rf#5]
I have tried to set up this custom component with a NodeMCU and a CC1101, but I get the following messages:
```
CC1101 found with partnum: 0 and version: 0
Failed to write CC1101 config register
Failed to reset CC1101 modem. Check connection.
```
I have checked the connection multiple times, so it should work based on that. I have also tried with a different ESP module without success. If is disconnect the CC1101, the log changes to `partnum: ff and version: ff`

The GDO0 and the GDO2 pins are not connected, but based on the code it should work without it.

**Comment by nistvan86** [comment]
Hello.

Unfortunately I'm flying blind based on this, just as you.
That version number and partnum doesn't seem correct indeed. The partnum can be zero, but the version I believe is never 0.

Is the `Failed to write CC1101 config register` message appear such short way?
It should have mentioned the register and the write/read value which failed verification.

      ESP_LOGE(TAG, "Failed to write CC1101 config register. reg: %02x write: %02x read: %02x", Q7RF_REG_CONFIG[i],
               Q7RF_REG_CONFIG[i + 1], verify_value);

**Comment by nistvan86** [comment]
Maybe try flashing the [example in this project](https://github.com/mrfaptastic/Easy-IoT-Arduino-CC1101/tree/master/examples/PlatformIO_Simple_RX_TX) onto your NodeMCU and connect as described. Then see what it prints out on the serial monitor once you reset NodeMCU.
The examples seems to set the debug level high enough to print out all the registers and such.
If it doesn't work either, you might wired it up incorrectly, or you have a bad module.

**Comment by spupetic** [comment]
Hi

Thank you for the tips. I have tried it with the example project, unfortunately without success. It seems like the module is dead. If I connect the GDO0 pin to the NodeMCU, it goes into a bootloop. The log message mentioned the exact register write/read value, I have just shortened it.

The exact messages were these:
```
[D][spi_device:369]: mode 0, data_rate 1kHz
[D][q7rf.switch:172]: Issued CC1101 reset sequence.
[I][q7rf.switch:181]: CC1101 found with partnum: 00 and version: 00
[E][q7rf.switch:189]: Failed to write CC1101 config register. reg: 06 write: 3d read: 00
[E][q7rf.switch:343]: Failed to reset CC1101 modem. Check connection.
```

**Comment by nistvan86** [comment]
I'm sorry to hear that :(
Yeah, it seems like the module answers to everything with 00's only. Interesting.
I can't seem to find anything related to this on the net.
It almost like if the internal oscillator of the chip is not running for some reason.

I hope you have better luck with another module.
